### ISSUE TITLE
LinkedNotebooks not returning notes

### ISSUE THREAD

**Issue by Adzter** [evernote/evernote-cloud-sdk-windows#29] opened 2016-09-04 12:49 UTC
Reading through the documentation and forum posts I understand data is hosted across multiple shards the LinkedNotebook may be on a different shard so it needs separate authentication. However the documentation states:

> Do not instantiate the store clients directly. The session will handle authenticating to linked and business note stores for you automatically.

However when running:
`ENSession.SharedSession.FindNotes(ENNoteSearch.NoteSearch(search), scope, ENSession.SearchScope.All, ENSession.SortOrder.RecentlyUpdated, 0);`

No results are returned for my LinkedNotebook. If I put the same notes into my "First notebook" then it's able to pick them up just fine.

I'm now very confused as to if I should be authenticating or not?

**Comment by mpnow** [comment] 2016-09-04 13:43
One of the reasons for the creation of this second iteration of the SDKs was to handle all of the multiple authentications, different shards, etc. for you, so you don't have to worry about it (in the first version of the SDKs you did have to do the multiple authentications, etc. yourself). So no, you don't need to authenticate to your LinkedNotebook.

In terms of your specific case: 
- What's the value of `scope`?
- If you do a `ListNotebooks` call, is the LinkedNotebook in question contained in the resulting list?

**Comment by Adzter** [comment] 2016-09-04 13:57
Ah, that's great that the SDK handles multiple shards and authentications. Apologies for the lack of context in my example, i'll expand:

I have a helper function for getting notes which you can pass a notebook to as well as a string to search for:

```
public List<ENSessionFindNotesResult> get_notes( String search, ENNotebook scope )
{
    return ENSession.SharedSession.FindNotes(ENNoteSearch.NoteSearch(search), scope, ENSession.SearchScope.All, ENSession.SortOrder.RecentlyUpdated, 0);
}
```

Here's the contents of the values that I'm passing
![Values](https://i.imgur.com/f1V73Zz.png)

This will return nothing even though it's 100% valid. Even if I change my search term to search only for notes after 2007 it'll not return anything.

If I do ListNotebooks it does indeed show up there as well. The general flow of my program is that the user is presented with a drop down populated from ListNotebooks, the selected notebook is then passed to my helper function.

**Comment by mpnow** [comment] 2016-09-04 14:27
What happens if you set `search` equal to an empty string? You should then get back all notes in that ENNotebook (you can set `maxResults` to a non-zero value if you're concerned that might return a huge number of matches - I'm just looking to see if you can get anything back from that notebook in the simplest search scenario of no other criteria to match).

**Comment by Adzter** [comment] 2016-09-04 14:46
Using the search term

`ENSession.SharedSession.FindNotes(ENNoteSearch.NoteSearch(""), scope, ENSession.SearchScope.All, ENSession.SortOrder.RecentlyUpdated, 0);`

will return me "null".

**Comment by mpnow** [comment] 2016-09-04 14:58
Hmm, I just tested your scenario and am able to reproduce the problem. I'm investigating further.

**Comment by mpnow** [comment] 2016-09-04 16:03
OK, it's a bug in the Windows SDK. In my defense (I initially wrote this SDK), it was based on the iOS SDK which it turns out had the same bug at the time. The bug was [since identified and fixed in the iOS SDK](https://github.com/evernote/evernote-cloud-sdk-ios/issues/34) but that fix didn't get made in the Windows SDK.

I'll submit a fix here within an hour or so.

**Comment by mpnow** [comment] 2016-09-04 18:00
I've checked in a fix for this issue.

**Closed as completed** 2016-09-04 19:42 UTC

**Comment by mpindado** [comment] 2016-10-05 06:50
Hi, I've just run into this issue. Will you update the nuget package? Thank you.
